"""empty message

Revision ID: 511aee2d7b55
Revises: a294bcd05eb8
Create Date: 2019-06-02 10:47:58.023201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511aee2d7b55'
down_revision = 'a294bcd05eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated')
    # ### end Alembic commands ###
