"""empty message

Revision ID: 7b5ce18494c5
Revises: 
Create Date: 2019-05-19 10:22:23.848675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5ce18494c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
        sa.Column('link', sa.String(length=200), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('price', sa.String(length=10), nullable=True),
        sa.Column('image', sa.String(length=200), nullable=True),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('link'),
        sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
