"""empty message

Revision ID: a294bcd05eb8
Revises: 7b5ce18494c5
Create Date: 2019-06-01 12:57:06.228618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a294bcd05eb8'
down_revision = '7b5ce18494c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'active')
    # ### end Alembic commands ###
