"""Add Categories model

Revision ID: d51e55c16a35
Revises: 511aee2d7b55
Create Date: 2020-02-01 22:37:15.584395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51e55c16a35'
down_revision = '511aee2d7b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=120), nullable=True),
        sa.Column('slug', sa.String(length=50), nullable=True),
        sa.Column('path', sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_path'), 'category', ['path'], unique=False)
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))

    with op.batch_alter_table("products") as batch_op:
        batch_op.create_foreign_key("products_category", 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products") as batch_op:
        batch_op.drop_constraint("products_category", type_='foreignkey')

    op.drop_column('products', 'category_id')
    op.drop_index(op.f('ix_category_path'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
